#!/bin/sh
# Generated by DeepSeek: 
# aesdsocket-start-stop - Simple startup script for aesdsocket daemon
#
# Usage: aesdsocket-start-stop {start|stop|restart|status}
#

NAME="aesdsocket"
DAEMON="/usr/bin/${NAME}"
PIDFILE="/var/run/${NAME}.pid"

# Check if start-stop-daemon exists
if ! command -v start-stop-daemon >/dev/null 2>&1; then
    echo "Error: start-stop-daemon not found" >&2
    exit 1
fi

# Check if daemon exists
if [ ! -x "${DAEMON}" ]; then
    echo "Error: ${DAEMON} not found or not executable" >&2
    exit 1
fi

start() {
    echo "Starting ${NAME}..."
    if start-stop-daemon --start --quiet --background \
        --pidfile "${PIDFILE}" --make-pidfile \
        --exec "${DAEMON}" -- -d; then
        echo "OK"
        return 0
    else
        echo "Failed"
        return 1
    fi
}

stop() {
    echo "Stopping ${NAME}..."
    if start-stop-daemon --stop --quiet --retry=TERM/10/KILL/5 \
        --pidfile "${PIDFILE}" --exec "${DAEMON}"; then
        # Clean up PID file
        rm -f "${PIDFILE}"
        echo "OK"
        return 0
    else
        echo "Failed"
        return 1
    fi
}

status() {
    if [ -f "${PIDFILE}" ]; then
        PID=$(cat "${PIDFILE}" 2>/dev/null)
        if [ -n "${PID}" ] && kill -0 "${PID}" 2>/dev/null; then
            echo "${NAME} is running (pid ${PID})"
            return 0
        else
            echo "${NAME} is not running (stale PID file)"
            rm -f "${PIDFILE}"
            return 1
        fi
    else
        echo "${NAME} is not running"
        return 1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 1
        start
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit $?
